### ISSUE TITLE
Error Output:  panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1910ce5] goroutine 1 [running]: github.com/pingcap/tidb/util/memory.MemTotalNormal() pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20210601085537-5d7c852770eb/util/memory/meminfo.go:41 +0x65 github.com/pingcap/tidb/util/memory.init.0() pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20210601085537-5d7c852770eb/util/memory/meminfo.go:134 +0x175

### ISSUE THREAD

**Issue by LittleHans8** [guanguans/laravel-soar#32]
**Describe the bug**

-------------
Error Output: ================ panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1910ce5] goroutine 1 [running]: github.com/pingcap/tidb/util/memory.MemTotalNormal() pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20210601085537-5d7c852770eb/util/memory/meminfo.go:41 +0x65 github.com/pingcap/tidb/util/memory.init.0() pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20210601085537-5d7c852770eb/util/memory/meminfo.go:134 +0x175

**To Reproduce**
1. 安装后访问任意页面都报错，尝试去掉所有参数还是一样报错。
2. 看日志是二进制包的问题，但奇怪的是在命令行却可以正常输出结果。

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/15800501/218702172-283cee29-1ab0-419c-8918-3b9efc9a192e.png">

**Screenshots**
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/15800501/218687480-bbcdc626-3e6f-42c7-9d9e-47a774a42826.png">

**Additional context**

- macos 13.2

- php
PHP 8.2.0 (cli) (built: Dec  9 2022 16:30:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.0, Copyright (c), by Zend Technologies

**Comment by guanguans** [comment]
@LittleHans8 这样看来确实很奇怪，我这边没法还原你的运行环境。建议你手动配置下 arm 的 soar 文件试试。
